name: Mijn.host DDNS Updater
version: "1.0.1"
slug: mijn_host_ddns_updater
description: Update Mijn.host DNS records with the current public IP address.
url: https://github.com/MarQuez-Mr/mijn_host_dns_updater_ha
arch:
  - amd64
  - aarch64
  - armv7
startup: application
boot: auto
init: false
options:
  api_key: null
  domain_name: null
  record_names:
    - "@"
  default_ttl: 300
  create_records_if_missing: false
  interval: 1800
schema:
  api_key: password
  domain_name: str
  record_names:
    - str
  default_ttl: int(1,)
  create_records_if_missing: bool
  interval: int(0,)
